Adding the Warning message whenever a terms is created within a same …
opendatadiscovery/odd-platform pull request #1696
Opened 2024-08-02 16:08 UTC by mavenzer

This is the MR https://github.com/opendatadiscovery/odd-platform/issues/1695  for the issue which we raised. Attaching the screenshot for the couple of terms tested from our end with the warning/error message.

![term-duplication](https://github.com/user-attachments/assets/30bf6cad-43a8-4a94-a637-16b123a3045d)

2024-08-12 16:02 UTC, AndreyNenashev requested changes
@mavenzer There is something wrong happened with margins.

2024-08-13 13:07 UTC, mavenzer commented
@AndreyNenashev I will look into it.

2024-08-17 16:48 UTC, mavenzer commented
@AndreyNenashev  I have added the margins whenever the alert is popped up, Attaching a screenshot for reference. Please have a look and let me know if there are any issues. 
![v25](https://github.com/user-attachments/assets/8403314a-59bf-49a7-8fd0-fc1af1f7755c)

2024-08-19 12:04 UTC, AndreyNenashev approved these changes

2024-08-19 12:04 UTC, merged