Enhancement/ingestion unit tests
opendatadiscovery/odd-platform pull request #491
Opened 2022-02-24 13:06 UTC by esmeneev

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing applications:)

**What changes did you make?** (Give an overview)
Implements unit tests for IngestionService that cover ingesting data entities for both existing and new entities, as well as ingesting dependencies(lineage, etc) and dataset structure. While this is definitely not a full coverage of the aforementioned service, I think this PR lays the groundwork for further unit testing of both this and other services.
**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "X" next to an item)

- [ ] No need to
- [ ] Manually(please, describe, when necessary)
- [X] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "X" next to an item, otherwise PR will fail)
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

Check out [Contributing](https://github.com/opendatadiscovery/odd-platform/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/opendatadiscovery/odd-platform/blob/main/CODE_OF_CONDUCT.md)

2022-03-15 12:54 UTC, damirabdul approved these changes

2022-03-15 12:59 UTC, damirabdul commented on odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/utils/JSONSerDeUtils.java
> +    public static <T> T deserializeJson(final File file, final TypeReference<T> tr) {
please create Util class in test sources, since this method will not be used outside of tests

2022-03-15 12:59 UTC, DementevNikita requested changes

2022-03-15 12:59 UTC, DementevNikita commented on odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/utils/JSONSerDeUtils.java
> +    public static <T> T deserializeJson(final File file, final TypeReference<T> tr) {
Please do not populate main code with the test-designed one. Let's move this method into some test utils class

2022-03-16 14:58 UTC, esmeneev commented
@DementevNikita could you please re-review?

2022-03-17 11:03 UTC, DementevNikita approved these changes

2022-03-17 11:04 UTC, merged