#620: Refactor Lineage to reactive
opendatadiscovery/odd-platform pull request #817
Opened 2022-07-14 15:28 UTC by esmeneev

**What changes did you make?** (Give an overview)
Refactored `LineageRepository`, `GroupEntityRelationRepository` and `LineageService` to reactive approach.

Tests and refactoring of `LineageMapper` still pending.

**Is there anything you'd like reviewers to focus on?**

**How to test**
Will be covered by unit tests, also can be tested by calling respective endpoints (`GET /api/dataentities/{data_entity_id}/lineage/downstream`, `GET /api/dataentities/{data_entity_id}/lineage/upstream` and `GET /api/dataentitygroups/{data_entity_group_id}/lineage`)

2022-07-26 15:10 UTC, damirabdul requested changes
Please don't forget to delete unused methods from blocking repositories

2022-07-26 15:10 UTC, damirabdul commented on odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/LineageServiceImpl.java
> +                        .map(tuple -> {
you can use TupleUtils.finction() for giving names to tuples components. There are a lot of examples in codebase

2022-07-26 15:10 UTC, damirabdul commented on odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/LineageServiceImpl.java
> +                        .map(tuple -> {
Can we extract peaces of code from this map to small methods?

2022-08-10 21:39 UTC, esmeneev commented on odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveLineageRepositoryImpl.java
> +    public Mono<LineagePojo> replaceLineagePaths(final List<LineagePojo> pojos) {
Fixed by moving replaceLineagePaths to service.

2022-08-10 21:39 UTC, esmeneev commented on odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/repository/reactive/ReactiveLineageRepositoryImpl.java
> +            .execute();
Fixed by moving replaceLineagePaths to service.

2022-09-11 12:57 UTC, damirabdul approved these changes

2022-09-12 16:08 UTC, merged